#!/usr/bin/env bash
set -e

READ_ONLY=1 lein build-app production
git checkout gh-pages
cp -Rfv out/public/* .
rm -rf generated-js/out/
mv semtag-web.html index.html
git add generated-js *.css *.js index.html
git commit -m "Assets rebuilt"
